module.exports = {
  findByPost: require('./findByPost'),
  appendVotes: require('./appendVotes'),
  findComment: require('./findComment'),
  addComment: require('./addComment'),
  editComment: require('./editComment'),
  deleteComment: require('./deleteComment'),
  setRating: require('./setRating'),
  deleteRating: require('./deleteRating'),
  findProfile: require('./findProfile'),
  findBackup: require('./findBackup'),
  createUser: require('./createUser'),
  userStatus: require('./userStatus'),
  getIdentity: require('./getIdentity'),
  addProfile: require('./addProfile'),
  updateAvatar: require('./updateAvatar'),
  loadAvatar: require('./loadAvatar'),
  findNotifications: require('./findNotifications'),
  setNotification: require('./setNotification')
}
